from flask import Flask

# Initialize the Flask application
app = Flask(__name__)

# HTML template for the game, including embedded CSS and JavaScript
HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tic Tac Toe</title>
    <style>
        /* Basic styling for the entire page */
        body {
            font-family: 'Arial', sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background-color: #f0f2f5;
            color: #333;
        }

        /* Main container for the game */
        .game-container {
            text-align: center;
            background-color: white;
            padding: 40px;
            border-radius: 15px;
            box-shadow: 0 10px 20px rgba(0, 0, 0, 0.1);
        }

        h1 {
            margin-bottom: 20px;
            font-size: 2.5rem;
            color: #1a73e8;
        }

        /* Styling for the game board grid */
        .board {
            display: grid;
            grid-template-columns: repeat(3, 100px);
            grid-template-rows: repeat(3, 100px);
            gap: 10px;
            margin: 20px auto;
        }

        /* Styling for each cell in the board */
        .cell {
            width: 100px;
            height: 100px;
            background-color: #e8eaed;
            border-radius: 10px;
            display: flex;
            justify-content: center;
            align-items: center;
            font-size: 3rem;
            font-weight: bold;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        .cell:hover {
            background-color: #dcdde1;
        }

        /* Specific styling for X and O marks */
        .cell.x {
            color: #ea4335;
        }

        .cell.o {
            color: #34a853;
        }

        /* Game status message area */
        .status {
            margin-bottom: 20px;
            font-size: 1.5rem;
            height: 30px; /* Reserve space to prevent layout shift */
        }

        /* Restart button styling */
        .restart-btn {
            background-color: #1a73e8;
            color: white;
            border: none;
            padding: 12px 25px;
            font-size: 1rem;
            border-radius: 8px;
            cursor: pointer;
            transition: background-color 0.3s ease, transform 0.2s ease;
        }

        .restart-btn:hover {
            background-color: #1558b3;
            transform: translateY(-2px);
        }
    </style>
</head>
<body>

    <div class="game-container">
        <h1>Game TicTacToe</h1>
        <div class="status" id="status-message">Player X's turn</div>
        <div class="board" id="board">
            <!-- Cells will be generated by JavaScript -->
        </div>
        <button class="restart-btn" id="restart-button">Restart Game</button>
    </div>

    <script>
        // DOM element references
        const boardElement = document.getElementById('board');
        const statusMessageElement = document.getElementById('status-message');
        const restartButton = document.getElementById('restart-button');

        // Game state variables
        let gameActive = true;
        let currentPlayer = 'X';
        let gameState = ["", "", "", "", "", "", "", "", ""];

        // All possible winning combinations on the board
        const winningConditions = [
            [0, 1, 2],
            [3, 4, 5],
            [6, 7, 8],
            [0, 3, 6],
            [1, 4, 7],
            [2, 5, 8],
            [0, 4, 8],
            [2, 4, 6]
        ];

        // Messages to display to the user
        const winningMessage = () => `Player ${currentPlayer} has won!`;
        const drawMessage = () => `Game ended in a draw!`;
        const currentPlayerTurn = () => `Player ${currentPlayer}'s turn`;

        // --- Game Logic Functions ---

        // Function to create the board cells
        function createBoard() {
            for (let i = 0; i < 9; i++) {
                const cell = document.createElement('div');
                cell.classList.add('cell');
                cell.dataset.cellIndex = i;
                cell.addEventListener('click', handleCellClick);
                boardElement.appendChild(cell);
            }
        }

        // Function to handle a click on a cell
        function handleCellClick(clickedCellEvent) {
            const clickedCell = clickedCellEvent.target;
            const clickedCellIndex = parseInt(clickedCell.dataset.cellIndex);

            // If the cell is already played or the game is over, do nothing
            if (gameState[clickedCellIndex] !== "" || !gameActive) {
                return;
            }

            // Process the move
            handleCellPlayed(clickedCell, clickedCellIndex);
            handleResultValidation();
        }

        // Function to update the game state after a move
        function handleCellPlayed(clickedCell, clickedCellIndex) {
            gameState[clickedCellIndex] = currentPlayer;
            clickedCell.innerHTML = currentPlayer;
            clickedCell.classList.add(currentPlayer.toLowerCase());
        }

        // Function to check for a win or a draw
        function handleResultValidation() {
            let roundWon = false;
            for (let i = 0; i < winningConditions.length; i++) {
                const winCondition = winningConditions[i];
                let a = gameState[winCondition[0]];
                let b = gameState[winCondition[1]];
                let c = gameState[winCondition[2]];

                if (a === '' || b === '' || c === '') {
                    continue; // Skip if any cell in the condition is empty
                }
                if (a === b && b === c) {
                    roundWon = true;
                    break;
                }
            }

            if (roundWon) {
                statusMessageElement.innerHTML = winningMessage();
                gameActive = false;
                return;
            }

            // Check for a draw (if all cells are filled and no winner)
            let roundDraw = !gameState.includes("");
            if (roundDraw) {
                statusMessageElement.innerHTML = drawMessage();
                gameActive = false;
                return;
            }

            // If no win or draw, switch to the next player
            handlePlayerChange();
        }

        // Function to switch the current player
        function handlePlayerChange() {
            currentPlayer = currentPlayer === "X" ? "O" : "X";
            statusMessageElement.innerHTML = currentPlayerTurn();
        }

        // Function to restart the game
        function handleRestartGame() {
            gameActive = true;
            currentPlayer = "X";
            gameState = ["", "", "", "", "", "", "", "", ""];
            statusMessageElement.innerHTML = currentPlayerTurn();
            // Clear all cells
            document.querySelectorAll('.cell').forEach(cell => {
                cell.innerHTML = "";
                cell.classList.remove('x', 'o');
            });
        }

        // --- Event Listeners and Initial Setup ---

        // Set up the restart button
        restartButton.addEventListener('click', handleRestartGame);

        // Initialize the game board on page load
        createBoard();
        statusMessageElement.innerHTML = currentPlayerTurn();

    </script>
</body>
</html>
"""

# Define the main route for the web application
@app.route('/')
def tic_tac_toe():
    """
    This function serves the main HTML page for the Tic Tac Toe game.
    """
    return HTML_TEMPLATE

# Main entry point to run the application
if __name__ == '__main__':
    # You can run this script and access the game at http://127.0.0.1:5000
    app.run(debug=True, port=5000)
